version: '3'

services:
  nlp:
    build: .
    image: cornatul/nlp:v1
    container_name: nlp
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app/
