FROM python:3.10
RUN apt update
RUN apt install curl -y
RUN su -c "pip install --upgrade pip"

## Uses "Spaceship" theme with some customization. Uses some bundled plugins and installs some more from github
#RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
#    -t https://github.com/denysdovhan/spaceship-prompt \
#    -a 'SPACESHIP_PROMPT_ADD_NEWLINE="false"' \
#    -a 'SPACESHIP_PROMPT_SEPARATE_LINE="false"' \
#    -p git \
#    -p ssh-agent \
#    -p https://github.com/zsh-users/zsh-autosuggestions \
#    -p https://github.com/zsh-users/zsh-completions
#
#
#RUN wget http://www.mirbsd.org/~tg/Debs/sources.txt/wtf-bookworm.sources
#RUN mkdir -p /etc/apt/sources.list.d
#RUN mv wtf-bookworm.sources /etc/apt/sources.list.d/
#RUN apt update
#
#RUN apt install openjdk-17-jdk -y
#
#RUN java --version

# Common Software
#RUN apt install software-properties-common -y


WORKDIR /app/
COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

ADD . /app/


#
#
#RUN su -c "curl -s https://deb.nodesource.com/setup_16.x | bash"
#RUN su -c "apt install nodejs -y"
#RUN su -c "apt install npm -y"
#RUN su -c "apt install net-tools -y"
#RUN su -c "npm install -g lighthouse"
#RUN su -c "apt install chromium -y"
#RUN su -c "pip3 install git+https://github.com/Cornatul/lighthouse-python.git#egg=lighthouse"
#RUN su -c "pip3 install html5lib"
#RUN su -c "pip3 install selenium"
#RUN su -c "pip3 install python-dotenv"
#RUN su -c "pip3 install tomd"
#RUN su -c "pip3 install pandoc"
#RUN su -c "pip3 install pytrends"
#RUN su -c "pip3 install tweepy"
#RUN su -c "pip3 install python-decouple"
#RUN su -c "pip3 install pypandoc"
#RUN su -c "pip3 install prompt_toolkit"
#RUN su -c "pip3 install rich"
#RUN su -c "pip3 install uvicorn"
#RUN su -c "pip3 install pydantic"
#RUN su -c "pip3 install google-search-results"
#RUN su -c "pip3 install socials"
#RUN su -c "pip3 install feedfinder2"
#RUN su -c "pip3 install pika"
#RUN su -c "pip3 install pyseoanalyzer"
#RUN su -c "pip3 install email-validator"
#RUN su -c "pip3 install markdownify"
#RUN su -c "pip3 install newspaper3k"
#RUN su -c "pip3 install fastapi"
#RUN su -c "pip3 install feedparser"
#RUN su -c "pip3 install pydantic"
#RUN su -c "pip3 install pysocks"
#RUN su -c "pip3 install requests"
#RUN su -c "pip3 install GoogleNews"
RUN su -c "pip3 install gnews"
RUN su -c "pip3 install uvicorn"
#RUN su -c "pip3 install vaderSentiment"
#RUN su -c "pip3 install spacy"
#RUN su -c "pip3 install spacy-html-tokenizer"
#RUN su -c "pip3 install spacy-dbpedia-spotlight"
#
#
#RUN su -c "pip3 install nltk"
#RUN su -c "pip3 install textblob"
RUN su -c "python3 -m nltk.downloader -d /usr/local/share/nltk_data punkt"
RUN su -c "python3 -m nltk.downloader -d /usr/local/share/nltk_data stopwords"
RUN su -c "python3 -m nltk.downloader -d /usr/local/share/nltk_data vader_lexicon"
RUN su -c "python3 -m spacy download en_core_web_md"
RUN su -c "python3 -m textblob.download_corpora"


# Set labels for better maintainability
LABEL maintainer="Stefan <stefan@lzomedia.com>"
EXPOSE 5000
# Start the web server
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "5000"]
