version: '3'

services:
  api.todayintel.com:
    build: .
    image: cornatul/api.todayintel.com:v1
    container_name: api.todayintel.com
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - type: bind
        source: .
        target: /app/
