version: '3'

services:
  nlp:
    build: .
    image: cornatul/api.todayintel.com:v1
    container_name: nlp
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - type: bind
        source: .
        target: /app/
