version: '3'

services:
  traefik:
    image: traefik:v2.3
    restart: always
    command:
      - --accesslog
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:80"
      - "8080:8080"

  nlp:
    image: cornatul/api.todayintel.com:v1
    container_name: nlp
    restart: always
    deploy:
      replicas: 3
    environment:
      - APP_PORT=8000
    expose:
      - 8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.nlpservice.rule=Host(`api.todayintel.com`)
