version: '3.8'
services:
    nlp:
        image: cornatul/nlp:v1
        container_name: nlp
        ports:
            - 8000:8000
        volumes:
            - type: bind
              source: .
              target: /app/
