server:
  port: 8080

spring:
  codec:
    max-in-memory-size: -1
  profiles:
    active: secret
  main:
    allow-bean-definition-overriding: true

management:
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always
    configprops:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    ru.sokomishalov.skraper: debug
    org.zalando.logbook: trace